# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies without running scripts
RUN npm install --ignore-scripts

# Copy the rest of the application
COPY . ./

# Build the project
RUN npm run build

# Expose port if necessary (not strictly required for stdio MCP server)

# Command to run the server
CMD ["node", "dist/index.js"]
